# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgiwa', '0002_auto_20160515_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browser',
            name='support_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
