# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgiwa', '0003_auto_20160515_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
