# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgiwa', '0004_operatingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser',
            name='operating_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgiwa.OperatingSystem'),
            preserve_default=False,
        ),
    ]
