# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgiwa', '0007_url_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_description',
            field=models.CharField(default='some desc', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defect',
            name='screenshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgiwa.Screenshot'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
