# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgiwa', '0008_auto_20160524_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_request',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='tgiwa.TestRequest'),
            preserve_default=False,
        ),
    ]
